version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=nxadmin
      - POSTGRES_PASSWORD=nuxeo

  swarm:
    links:
      - db
    environment:
      - JAVA_OPTS=-Xms512m -Xmx3g
      - NX_DB_HOST=db

